### ISSUE TITLE
Add confirmation button in schedule delete

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/rubix-ce#1091]
https://user-images.githubusercontent.com/6800775/237049422-82358b78-bec5-4878-9149-9754ae40007e.mov

And sometimes the delete button doesn't appear or doesn't appear instantly after selecting the schedules as well.

**Comment by NubeDev** [comment]
remove `sec`

![image](https://github.com/NubeIO/rubix-ce/assets/18637436/8ebf9bd8-f8e1-4384-b24d-cd33d36e4b97)

**Comment by NubeDev** [comment]
no way to edit existing

![image](https://github.com/NubeIO/rubix-ce/assets/18637436/05710831-2059-4487-8c07-fe1123e6e12c)

**Comment by RaiBnod** [comment]
Also needs to integrate right-click option for this, as we are going to integrate the `SYNC` option sooner and it will be on right-click as in `Networks > Devices > Points`.
