### ISSUE TITLE
Issue on Add Location

### ISSUE THREAD

**Issue by CanuckMarc** [NubeIO/rubix-ce#1254]
Got the following error when trying to add a Location to the `nubeio` server. 

![image](https://github.com/NubeIO/rubix-ce/assets/40550860/5fa3d1e3-1b41-4200-b43d-7a7038f5e201)

**Comment by RaiBnod** [comment]
`nubeio` does have older `bios` and you are trying to add the newer one. That older server is not compatible with the newer one straight forward, we need some manual intervention in it. Here is the documentation:

https://github.com/NubeIO/rubix-os/issues/26

We can't go back into the older version, once we apply that. So, if you need to convert `nubeio` server into latest one, let me know.

**Comment by CanuckMarc** [comment]
I think my issue was that I needed to delete the `/data` directory
