### ISSUE TITLE
Table needs to scroll instead of the whole page

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/rubix-ce#1272]
See these on `Networks` > `Devices` > `Points` pages:

![Screenshot 2023-06-26 at 8 08 30 PM](https://github.com/NubeIO/rubix-ce/assets/6800775/555a953b-aa7e-47c5-abf8-5a5daa4d0392)

**Comment by nguyenoanh5597** [comment]
hi @ayush-shta, this style change is related to the PR below, hope it helps
https://github.com/NubeIO/rubix-ce/pull/1203
