### ISSUE TITLE
All devices are showing up in the Groups

### ISSUE THREAD

**Issue by RaiBnod** [NubeIO/rubix-ce#1382]
https://github.com/NubeIO/rubix-ce/assets/6800775/915890e5-b1f6-43d1-b8dc-b7461c0c44e1

**Comment by RaiBnod** [comment]
@JiaFei1991 I saw your changes here: https://github.com/NubeIO/rubix-ce/blob/a18f6db2905e996c4cb3f40881bb3380edf25ffb/frontend/src/components/hosts/hosts.tsx#L89-L94

Why did you change this? It is supposed to pull the hosts of respective groups only.

**Comment by JiaFei1991** [comment]
@RaiBnod Hi, yeah it was probably for testing and I forgot to change it back, I will fix this tomorrow!
